global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: stream-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["stream-gateway:8000"]

  - job_name: spark-streaming
    static_configs:
      - targets: ["spark-streaming:9108"]
